import path from 'node:path'
import type { DefaultTheme } from 'vitepress'
import { docsDir, groupByDirectory, scanContentFiles, sections, writeGeneratedFile } from './shared.ts'

function sidebarLink(route: string): string {
  return route.endsWith('/') ? route : route.replace(/\.md$/, '')
}

function createSidebar(files: Awaited<ReturnType<typeof scanContentFiles>>): DefaultTheme.Config['sidebar'] {
  const sidebar: DefaultTheme.Config['sidebar'] = {}

  for (const section of sections) {
    const markdownFiles = files.filter((file) => file.section === section.directory && file.extension === '.md')
    const items = markdownFiles.map((file) => ({
      text: file.title,
      link: sidebarLink(file.route)
    }))

    sidebar[`/${section.directory}/`] = [
      {
        text: section.label,
        items: items.length > 0 ? items : [{ text: section.indexTitle, link: `/${section.directory}/` }]
      }
    ]
  }

  return sidebar
}

function renderSidebar(sidebar: DefaultTheme.Config['sidebar']): string {
  return `// This file is generated by scripts/generate-index.ts.\n// Do not edit it by hand.\n\nimport type { DefaultTheme } from 'vitepress'\n\nexport const generatedSidebar: DefaultTheme.Config['sidebar'] = ${JSON.stringify(sidebar, null, 2)}\n`
}

function renderDirectoryIndex(sectionLabel: string, directory: string, files: Awaited<ReturnType<typeof scanContentFiles>>): string {
  const groups = groupByDirectory(files)
  const lines = [
    '<!-- This file is generated by scripts/generate-index.ts. Do not edit it by hand. -->',
    '',
    `# ${sectionLabel}`,
    '',
    '本页由仓库中的 Markdown 和 PDF 文件自动生成。新增资料后，运行 `npm run generate` 即可刷新。',
    ''
  ]

  const sortedGroups = Array.from(groups.entries())
    .filter(([groupDirectory]) => groupDirectory === directory || groupDirectory.startsWith(`${directory}/`))
    .sort(([a], [b]) => a.localeCompare(b, 'zh-CN'))

  for (const [groupDirectory, groupFiles] of sortedGroups) {
    const heading = groupDirectory === directory ? sectionLabel : groupDirectory.replace(`${directory}/`, '').replace(/[-_]/g, ' / ')
    const visibleFiles = groupFiles.filter((file) => file.extension === '.md' && !file.relativePath.endsWith('/index.md'))

    if (visibleFiles.length === 0) {
      continue
    }

    lines.push(`## ${heading}`)
    lines.push('')

    for (const file of visibleFiles) {
      lines.push(`- [${file.title}](${file.route})`)
    }

    lines.push('')
  }

  lines.push('## 下载资料')
  lines.push('')
  lines.push('PDF 下载链接会在 [下载列表](./downloads) 中自动整理。')
  lines.push('')

  return `${lines.join('\n')}\n`
}

const files = await scanContentFiles()
const sidebar = createSidebar(files)

await writeGeneratedFile(path.join(docsDir, '.vitepress/generated/sidebar.ts'), renderSidebar(sidebar))

for (const section of sections) {
  if (section.directory === 'contribution') {
    continue
  }

  const sectionFiles = files.filter((file) => file.section === section.directory)
  await writeGeneratedFile(
    path.join(docsDir, section.directory, 'index.md'),
    renderDirectoryIndex(section.indexTitle, section.directory, sectionFiles)
  )
}

console.log(`Generated sidebar and ${sections.length} section index pages.`)


