import { copyFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { docsDir, publicHref, routeFromRelativePath, scanContentFiles, sections, writeGeneratedFile } from './shared.ts'

type DownloadFile = {
  title: string
  href: string
  type: string
}

async function copyPdfToPublic(relativePath: string, absolutePath: string) {
  const publicPath = path.join(docsDir, 'public', relativePath)
  await mkdir(path.dirname(publicPath), { recursive: true })
  await copyFile(absolutePath, publicPath)
}

function renderDownloadPage(title: string, pdfFiles: Awaited<ReturnType<typeof scanContentFiles>>): string {
  const lines = [
    '<!-- This file is generated by scripts/generate-downloads.ts. Do not edit it by hand. -->',
    '',
    `# ${title}下载列表`,
    '',
    '本页自动收集当前目录下的 PDF 文件。若同名 Markdown 页面存在，请优先阅读网页版本；PDF 适合作为原始试卷、扫描件或讲义附件。',
    ''
  ]

  if (pdfFiles.length === 0) {
    lines.push('暂无 PDF 下载资料。')
    lines.push('')
    return `${lines.join('\n')}\n`
  }

  for (const file of [...pdfFiles].sort((a, b) => Number(a.title.includes('答案')) - Number(b.title.includes('答案')) || a.title.localeCompare(b.title, 'zh-CN'))) {
    lines.push(`- [下载 ${file.title}](/${file.relativePath})`)
  }

  lines.push('')
  return `${lines.join('\n')}\n`
}

function isRelatedPdf(markdownPath: string, pdfPath: string): boolean {
  const markdownDirectory = path.dirname(markdownPath)
  const pdfDirectory = path.dirname(pdfPath)

  if (markdownDirectory !== pdfDirectory) {
    return false
  }

  const markdownStem = path.basename(markdownPath, '.md')
  const pdfStem = path.basename(pdfPath, '.pdf')
  return pdfStem === markdownStem || pdfStem.startsWith(`${markdownStem}-`)
}

const files = await scanContentFiles()
const markdownFiles = files.filter((file) => file.extension === '.md')
const pdfFiles = files.filter((file) => file.extension === '.pdf')
const downloadsByPage: Record<string, DownloadFile[]> = {}

for (const pdfFile of pdfFiles) {
  await copyPdfToPublic(pdfFile.relativePath, pdfFile.absolutePath)
}

for (const markdownFile of markdownFiles) {
  const relatedPdfs = pdfFiles
    .filter((pdfFile) => isRelatedPdf(markdownFile.relativePath, pdfFile.relativePath))
    .sort((a, b) => Number(a.title.includes('答案')) - Number(b.title.includes('答案')) || a.title.localeCompare(b.title, 'zh-CN'))

  if (relatedPdfs.length === 0) {
    continue
  }

  downloadsByPage[routeFromRelativePath(markdownFile.relativePath)] = relatedPdfs.map((pdfFile) => ({
    title: pdfFile.title,
    href: publicHref(pdfFile.relativePath),
    type: pdfFile.title.includes('答案') || pdfFile.title.toLowerCase().includes('solution') ? '下载答案' : '下载 PDF'
  }))
}

const downloadableSections = sections.filter((section) => section.directory !== 'contribution')

for (const section of downloadableSections) {
  const sectionPdfFiles = pdfFiles.filter((file) => file.section === section.directory)
  await writeGeneratedFile(
    path.join(docsDir, section.directory, 'downloads.md'),
    renderDownloadPage(section.label, sectionPdfFiles)
  )
}

const generatedModule = `// This file is generated by scripts/generate-downloads.ts.\n// Do not edit it by hand.\n\nexport type DownloadFile = {\n  title: string\n  href: string\n  type: string\n}\n\nexport const downloadsByPage: Record<string, DownloadFile[]> = ${JSON.stringify(downloadsByPage, null, 2)}\n`

await writeGeneratedFile(path.join(docsDir, '.vitepress/generated/downloads.ts'), generatedModule)
console.log(`Generated ${downloadableSections.length} download pages, copied ${pdfFiles.length} PDFs, and mapped ${Object.keys(downloadsByPage).length} pages.`)






